name: Latest blog post workflow every hour
on:
# Schedule updates (each hour)
    schedule: [{cron: "0 * * * *"}]
    # Lines below let you run workflow manually and on each commit
    workflow_dispatch:
    push: {branches: ["master", "main"]}
jobs:
    update-readme-with-blog:
        name: Update this repo's README with latest blog posts
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            - uses: actions/checkout@v2
            - uses: gautamkrishnar/blog-post-workflow@master
              with:
                max_post_count: "3"
                feed_list: "https://qrxnz.dev/index.xml"